### PR TITLE
Add ability to ignore columns from a model

### PR DESCRIPTION
**Pull request by nhocki**
When dumping a specific model we might want to skip some columns in the dump. This is specially helpful when those columns are encrypted and we don't have access to the keys to decrypt them.

We need to to this at the `dump!` level (and not as a customizer/anonymizer) because we don't want Rails to even query for the column without the decrypt keys (since that will raise an error).

### CODE REVIEW

**Comment by Envek** [comment]
Thanks for the pull request! I will take a look in a few days.

**Comment by Envek** [comment]
Can you please refresh this pull request?
I cherry-picked some of you secondary changes to master (and now there is a merge conflict) and set up Github Actions. Now I want CI to run tests against your pull request.

Alternatively, you can select “Allow edits from maintainers” option at the right column, then I will be able to refresh it myself.

**Comment by nhocki** [comment]
@Envek I've resolved the conflicts and also added access to maintainers. Thanks!

**Comment by Envek** [comment]
Released in version [0.5.0](https://rubygems.org/gems/evil-seed/versions/0.5.0). Thank you!

**Pull request merged**
